logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type: TRACE
server:
    port: 8080
spring:
    datasource:
        password: 12345
        url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
